### PR TITLE
Traefik v2 file provider

### PR DESCRIPTION
**Pull request by alexleach**
Hello,

As discussed in https://github.com/jupyterhub/traefik-proxy/pull/133 and https://github.com/jupyterhub/traefik-proxy/issues/97, I have done some work getting jupyterhub-traefik-proxy working with traefik v2. This PR should allow jupyterhub to work with the Traefik v2 file provider, but comes with some caveats (as mentioned in https://github.com/jupyterhub/traefik-proxy/pull/133 ):-

- TLS will not be enabled on any traefik router.
- JupyterHub services will bind to every traefik entrypoint defined in the static configuration.
- Consul and etcd providers are not functional.

Fixes are available for these (in https://github.com/alexleach/traefik-proxy/tree/Traefik_v2), but this PR aims to minimise the size of the patches. Features can then be introduced incrementally to ease reviewing.

Hope this helps as a starting point for getting traefik v2 support functional anyway! 🙂 

fixes https://github.com/2i2c-org/external/issues/29

### CODE REVIEW

**Comment by alexleach** [comment]
Hi @GeorgianaElena, hope this works as a starting point.

I'm sure the commit history is not as tidy as it could have been, maybe the rebasing didn't go exactly as planned(!), as I think it includes the tidying commits you already made to the `traefik-v2` branch... Not really sure tbh... Should I give it another go and try to tidy up the commit history?

Cheers,
Alex

**Comment by GeorgianaElena** [comment]
Hey @alexleach! This a great starting point, indeed :tada:

> I'm sure the commit history is not as tidy as it could have been, maybe the rebasing didn't go exactly as planned(!), as I think it includes the tidying commits you already made to the traefik-v2 branch... Not really sure tbh... Should I give it another go and try to tidy up the commit history?

Rebasing is difficult, especially for a PR this size, so don't worry! I gave it a shot too and rebased it against the `traefik-v2` branch and this is how it looks like:
https://github.com/jupyterhub/traefik-proxy/compare/traefik-v2...GeorgianaElena:traefik-v2-file?expand=1

I could push those changes on your branch and update this PR, but I would really appreciate it if before, you could take a look at the changes to make sure I didn't remove any useful info while solving merge conflicts. (The tests pass locally btw, so this is a good sign)

**Comment by alexleach** [comment]
Hi @GeorgianaElena,

thanks for the kind words and for tidying it up to how it should be! I think this looks much better, but I would like to do a git / vim diff between your repository and mine to check how the final working copies compare. Pushing to my branch sounds like a plan, not sure how else to go about it, but maybe now is a good point to raise a couple of points / considerations:-

- Is renaming `TraefikTomlProxy` to `TraefikFileProviderProxy` okay with you? On reflection, I think I prefer just `TraefikFileProxy`, as they're all 'Providers'. What do you think?
- I made a mistake and clearly rushed commit 3f5b6732207f93fd1c0ca1ec84a04f0012ccb774. I should have renamed `toml.md` to `file.md`, but I instead renamed it `yaml.md`. This should be amended.
- Commit 6d8b714aaf62bbd5af83383847c266ab9909c8ec is also a mistake, and shouldn't be in the commit history, where I'd effectively commented out some of the `test_` functions, by renaming them `_test`.
- The tests in your latest commit fail because of my changes to `requirements.txt`, where I'd commented out `toml` and `ruamel.yaml`. `toml` probably should be required, and definitely so for the tests, and `ruamel.yaml` is required by one of the dependencies anyway, so doesn't need to be explicitly required. Therefore, I think my changes to `requirements.txt` can be removed from the commit history, and we leave `toml` as a strict dependency. I took a stab at making the toml and ruamel.yaml requirements optional (at least one is required), but wasn't really convinced with my implementation, so probably best just to keep `toml` as required?

I'll have a more thorough comparison when I can and will get back to you on that anyway, but would be glad to hear your thoughts on the above in the meantime 🙂 

KR, Alex

**Comment by GeorgianaElena** [comment]
@alexleach, let me know when you feel comfortable with me pushing the rebased version of these changes on your branch.

Some ideas below about some of the points in the previous comment:

>Is renaming TraefikTomlProxy to TraefikFileProviderProxy okay with you? On reflection, I think I prefer just TraefikFileProxy, as they're all 'Providers'. What do you think?

I think the shorter version makes sense, as you said they are all `providers` `TraefikFileProxy`

> I made a mistake and clearly rushed commit 3f5b673. I should have renamed toml.md to file.md, but I instead renamed it yaml.md. This should be amended.
> Commit 6d8b714 is also a mistake, and shouldn't be in the commit history, where I'd effectively commented out some of the test_ functions, by renaming them _test.

It should be fairly easy to drop some of the commits, once we've rebased the PR against the latest version of `traefik-v2` branch.

> The tests in your latest commit fail because of my changes to requirements.txt, where I'd commented out toml and ruamel.yaml. toml probably should be required, and definitely so for the tests, and ruamel.yaml is required by one of the dependencies anyway, so doesn't need to be explicitly required. Therefore, I think my changes to requirements.txt can be removed from the commit history, and we leave toml as a strict dependency. I took a stab at making the toml and ruamel.yaml requirements optional (at least one is required), but wasn't really convinced with my implementation, so probably best just to keep toml as required?

I believe it would make our life much easier if both of them are listed as explicit requirements. At least until we find a reason against it, as it happened for the `etcd` and `consul` python clients.

**Comment by alexleach** [comment]
Hi @GeorgianaElena ,

Thanks for the responses to my comments. I've had a chance to have a look this morning and to compare the HEAD's of our branches both locally and then on github. The default compare view (Ref: [1]) shows all the commit history, which actually makes it really difficult to compare!

On github, just comparing the HEAD's by commit ID (Ref: [2]), we can see that there are just some minor differences to various version numbers in `install.py` and then a non-functional change in `conftest.py`.

I think that only one difference in `install.py` is relevant at this stage; most of the differences are to version numbers of the consul and etcd shown in the argument parser's epilog, but the differences that have a functional effect are the default versions installed of `consul` and `traefik`. The latter change (Ref: [3]) is especially important. In your HEAD, it will try and install traefik version 2.2.0 and in mine version 2.4.8. The only checksums present for traefik (in both our HEADs) are for versions `2.4.8`, `2.3.7` and `2.2.11`, so this needs to be updated. I'm actually surprised your github workflow succeeded when trying to install traefik, maybe it just issued a warning that the checksum wasn't present?

I haven't narrowed down which commit(s) actually introduced these differences, but I suppose that isn't relevant. Now we have found these differences, we can quite easily patch them in a new commit. The patch needs to be made locally it seems, showing the raw patch on github (Ref: [4]) shows the full commit history again, which is overkill...

Okay, so a to-do list (please let me know your comments):-

- I'm happy if you push to my local branch, I think you have a better idea of how to get this to work than I do!
- Patch all (?) version numbers, or just the relevant one(?) - as shown in the diff above (Ref: [2])
- New commit renaming TraefikFileProviderProxy to TraefikFileProxy / edit one of the initial commits where I renamed TraefikTomlProxy to TraefikFileProviderProxy?
- Drop erroneous commit mentioned above, re: commenting out test functions (https://github.com/jupyterhub/traefik-proxy/commit/6d8b714aaf62bbd5af83383847c266ab9909c8ec)
- Edit erroneous commit where I renamed toml.md to yaml.md (https://github.com/jupyterhub/traefik-proxy/commit/3f5b6732207f93fd1c0ca1ec84a04f0012ccb774) instead of file.md.
- Anything else, before moving on to traefik-v2-file-tls?

Please let me know your thoughts and how I can next help!

KR, Alex 🙂 

[1]: https://github.com/jupyterhub/traefik-proxy/compare/traefik-v2...GeorgianaElena:traefik-v2-file?expand=1
[2]: https://github.com/GeorgianaElena/traefik-proxy/compare/d0a40a6..23cc536
[3]: https://github.com/GeorgianaElena/traefik-proxy/compare/d0a40a6..23cc536#diff-82b5cb3b9c1d20ea426fd0dce9174b464dc222d3381b2d964edce27a8d761110R332
[4]: https://github.com/GeorgianaElena/traefik-proxy/compare/d0a40a6..23cc536.patch

**Comment by GeorgianaElena** [comment]
Hey @alexleach! Sorry for the long silence, but I had some days off and tried to stay away from the keyboard.

I followed your to-do list above and updated [my copy](https://github.com/jupyterhub/traefik-proxy/compare/traefik-v2...GeorgianaElena:traefik-v2-file?expand=1) of your branch (great catch of the default `traefik` version in the installer :tada:). When I tried to push the changes back into your branch, I got a 403 error.

Do you think you can add me as a contributor to your fork? The option should be under https://github.com/alexleach/traefik-proxy, `Settings` -> `Manage Access` -> `Invite collaborator` green button. I believe this should do the trick and allow me to push to your fork directly. Alternatively I think I could open a PR to your fork?

**Comment by alexleach** [comment]
Hi @GeorgianaElena ,

Thanks for getting back to me, I was wondering about the long silence, but no worries! Hope you had an enjoyable and well-deserved break from the keyboard! 😄 🌞 🏖️ 

You've probably got the invitation to be a collaborator by now. I imagine that this is a better idea, as I think it will allow you to tidy up the commit history (i.e. to delete / edit past commits), whereas opening a PR I think would probably allow you to add commits. Not sure tbh, but either way, you should be able to edit my fork as you like now!

Thanks for going through the check-list. Let me know how I can help next!

KR, Alex

**Comment by minrk** [comment]
closed by #145

**Pull request closed without merging**
