### PR TITLE
Throughput results updated

### PR DESCRIPTION
**Pull request by GeorgianaElena**
* Added the option to run the throughput measurement multiple times
* Redone the throughput results and plots

### CODE REVIEW

**Comment by GeorgianaElena** [comment]
@minrk, I realized that the throughput results for CHP, TomlProxy and EtcdProxy were measured on my old hardware and probably under different conditions (laptop plugged in) than the ConsulProxy.
I've reran the benchmark for all proxies, on the same hardware and in the same conditions and now the results make more sense.

**Comment by GeorgianaElena** [comment]
(Unrelated to this PR) When rerunning the benchmark I realized that I forgot to mention that we get some warnings when using TraefikConsulProxy (related to https://github.com/cablehead/python-consul/issues/226):
```
consul/aio.py:58: RuntimeWarning: coroutine 'ClientSession.close' was never awaited self._session.close()
Unclosed client session
...
Unclosed connector
```

**Comment by minrk** [comment]
Excellent! The results make a lot more sense now. Could you open an Issue about the unawaited close? It could be a missing `await` in our code.

**Comment by GeorgianaElena** [comment]
Sure!

**Comment by ashwini-balnaves** [comment]
> 
> 
> Excellent! The results make a lot more sense now. Could you open an Issue about the unawaited close? It could be a missing `await` in our code.

@minrk There is an issue for this (https://github.com/cablehead/python-consul/issues/226) and an open pr to fix this issue. (https://github.com/cablehead/python-consul/pull/231)

**Pull request merged**
