### PR TITLE
Fix link to traefik example

### PR DESCRIPTION
**Pull request by matuzalemmuller**
Quick fix in the doc.

Link is broken here: https://jupyterhub-traefik-proxy.readthedocs.io/en/latest/install.html#enabling-traefik-proxy-in-jupyterhub

### CODE REVIEW

**Review by manics — APPROVED** [review]
Thanks!

**Comment by minrk** [comment]
Sorry, should have responded quicker. This updates the link to a file that exists, but the description is not of that file. The fix should have been to create the missing file (perhaps someone forgot a `git add`), not update the link to a different file.

**Comment by minrk** [comment]
That someone was me! #261

**Comment by minrk** [comment]
No problem, thanks for noticing and submitting the PR!

**Pull request merged**
