### PR TITLE
trade versioneer for tbump

### LINKED ISSUE #90: Consider removing versioneer?
In a [recent PR](https://github.com/jupyterhub/traefik-proxy/pull/89) we discussed about the benefits of using versioneer for traefik-proxy.
This issue is meant to summarize our discussion and have it for future reference (in case problems may arrise).

Pros
------
* Creating releases is simpler because no files need to be edited (repo2docker's release process [benefits greatly from this](https://github.com/jupyter/repo2docker/issues/558))
* Development versions report their exact commit automatically (minor benefit unless development-version use is common)
* Autogenerated files handle many cases and are thus more complex than manually edited files.
* Easy to use

Cons
-------
* Installation from development versions other than the main git repo (git-archive, forks with out-of-date tags) works fine, but can report the wrong version (which may stop 'working fine' when dependencies enter into it)
* Autogenerated files handle many cases and are thus more complex than manually edited files.
* Hard to understand and debug
* versioneer may be unmaintained:
   - https://github.com/pytroll/satpy/issues/678
   - https://github.com/pydata/xarray/issues/2853

### PR DESCRIPTION
**Pull request by minrk**
I noticed in some tests that the 1.0.0b1 release doesn't self-identify with the right version, it calls itself `'0+untagged.502.g26ec31b'`. Rather than debugging versioneer, I figured it was simpler to switch to tbump, like we do in most other projects these days.

closes #90

### CODE REVIEW

**Review by consideRatio — COMMENTED** [review]
I love making this switch for a reduced complexity when considering our ecosystem of repos in the jh github org.

Changes requested:
- i saw jupyterhub/jupyterhub mentioned in release.md
- i saw markdown links with an empty square bracket after a named reference, and understand those to be something we are removing overall based on changes seen elsewhere in PRs

**Comment by consideRatio** [comment]
I've forgotten, i recall seeing you do this but maybe it was someone else. But since its style not autoformatted, i agree we shouldnt bother thinking about it.

**Review by consideRatio — APPROVED** [review]
LGTM, made another comment about dev-req - fine either way but i'm leaning towards having tbump be granted special treatment as a dependency

**Comment by minrk** [comment]
It may well have been me, or someone else. I don't think we should have a rule about it. I tend to use link references with the link target immediately after the paragraph to make it easier to read sentences without big links in the middle or sending links far away into a footnote, but I wouldn't object to either. In this case, it was just because that's how the jupyterhub doc I copied happens to do it.

**Comment by consideRatio** [comment]
I'm not 100% we speak about the same thing now, i meant the difference between "[linkref][]" and "[linkref]".

Review from my mobile with cold hands outdoors, sorry for potential confusion stemming from breif comments!

**Pull request merged**
